import { Car } from '@/types';

export const sampleCars: Car[] = [
  {
    id: 'toyota-harrier-2022',
    make: 'Toyota',
    model: 'Harrier',
    year: 2022,
    pricePerDay: 12000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    seats: 5,
    location: 'Westlands, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e825f79fd5e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dG95b3RhJTIwaGFycmllcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60',
    features: ['Premium Sound System', 'Leather Seats', 'Sunroof', 'Navigation', 'Backup Camera']
  },
  {
    id: 'toyota-rav4-2021',
    make: 'Toyota',
    model: 'RAV4',
    year: 2021,
    pricePerDay: 9500,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    seats: 5,
    location: 'Kilimani, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dG95b3RhJTIwcmF2NHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60',
    features: ['GPS', 'Bluetooth', 'Backup Camera', 'Apple CarPlay', 'All-Wheel Drive']
  },
  {
    id: 'subaru-forester-2020',
    make: 'Subaru',
    model: 'Forester',
    year: 2020,
    pricePerDay: 8500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Karen, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHN1YmFydSUyMGZvcmVzdGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60',
    features: ['All-Wheel Drive', 'Roof Rack', 'EyeSight Safety', 'X-Mode', 'Dual Zone Climate Control']
  },
  {
    id: 'nissan-x-trail-2021',
    make: 'Nissan',
    model: 'X-Trail',
    year: 2021,
    pricePerDay: 9000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 7,
    location: 'Mombasa',
    imageUrl: 'https://images.unsplash.com/photo-1621004989332-366b79ce8d01?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8bmlzc2FuJTIweHRyYWlsfGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60',
    features: ['Third Row Seating', '360 Camera', 'ProPILOT Assist', 'Premium Audio', 'Panoramic Sunroof']
  },
  {
    id: 'mazda-cx5-2021',
    make: 'Mazda',
    model: 'CX-5',
    year: 2021,
    pricePerDay: 8800,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Upper Hill, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1563720223880-4d93eef1f1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fG1hemRhJTIwY3g1fGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60',
    features: ['SkyActiv Technology', 'Bose Audio', 'Heated Seats', 'Head-Up Display', 'Power Liftgate']
  },
  {
    id: 'toyota-prado-2019',
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    year: 2019,
    pricePerDay: 15000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    seats: 7,
    location: 'Nakuru',
    imageUrl: 'https://images.unsplash.com/photo-1580273917197-8fb7ff3d4ab5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dG95b3RhJTIwcHJhZG98ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=600&q=60',
    features: ['4WD', 'Third Row Seating', 'Multi-Terrain Select', 'KDSS', 'Cool Box']
  },
  {
    id: 'honda-crv-2020',
    make: 'Honda',
    model: 'CR-V',
    year: 2020,
    pricePerDay: 8200,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Thika',
    imageUrl: 'https://images.unsplash.com/photo-1605651200238-83d5e5e45c9a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGhvbmRhJTIwY3J2fGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60',
    features: ['Honda Sensing', 'Eco Assist', 'Power Tailgate', 'Lane Watch', 'Dual Zone Climate Control']
  },
  {
    id: 'mercedes-glc-2021',
    make: 'Mercedes-Benz',
    model: 'GLC 300',
    year: 2021,
    pricePerDay: 18000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Gigiri, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1563720223880-4d93eef1f1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fG1hemRhJTIwY3g1fGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60',
    features: ['MBUX Infotainment', 'Panoramic Roof', 'Burmester Sound', 'Ambient Lighting', 'Parking Assist']
  },
  {
    id: 'suzuki-vitara-2021',
    make: 'Suzuki',
    model: 'Vitara',
    year: 2021,
    pricePerDay: 6500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Kisumu',
    imageUrl: 'https://images.unsplash.com/photo-1603712610494-73e1732b5c52?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c3V6dWtpJTIwdml0YXJhfGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60',
    features: ['AllGrip 4WD', 'Smartphone Linkage', 'Keyless Entry', 'Rear Camera', 'LED Headlights']
  },
  {
    id: 'toyota-hilux-2022',
    make: 'Toyota',
    model: 'Hilux Double Cab',
    year: 2022,
    pricePerDay: 11000,
    fuelType: 'Diesel',
    transmission: 'Manual',
    seats: 5,
    location: 'Naivasha',
    imageUrl: 'https://images.unsplash.com/photo-1580274437636-1c384e567539?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dG95b3RhJTIwaGlsdXh8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=600&q=60',
    features: ['4WD', 'Towing Package', 'Bed Liner', 'Off-Road tires', 'Snorkel']
  },
  {
    id: 'range-rover-sport-2020',
    make: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2020,
    pricePerDay: 25000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Karen, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1580273917197-8fb7ff3d4ab5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dG95b3RhJTIwcHJhZG98ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=600&q=60',
    features: ['Terrain Response', 'Meridian Sound', 'Panoramic Roof', 'Adaptive Dynamics', 'Touch Pro Duo']
  },
  {
    id: 'toyota-axio-2019',
    make: 'Toyota',
    model: 'Axio',
    year: 2019,
    pricePerDay: 4500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Eastleigh, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1549921296-3fdc4f58f2ad?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dG95b3RhJTIwYXhpb3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=600&q=60',
    features: ['Fuel Efficient', 'AC', 'Power Windows', 'CD Player', 'Central Locking']
  },
  {
    id: 'nissan-march-2018',
    make: 'Nissan',
    model: 'March',
    year: 2018,
    pricePerDay: 3500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Embakasi, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG5pc3NhbiUyMG1hcmNofGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60',
    features: ['Economical', 'Compact Size', 'Power Steering', 'Air Conditioning', 'FM Radio']
  },
  {
    id: 'subaru-outback-2021',
    make: 'Subaru',
    model: 'Outback',
    year: 2021,
    pricePerDay: 9500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Runda, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1603808033194-8d18d42c28bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHN1YmFydSUyMG91dGJhY2t8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=600&q=60',
    features: ['All-Wheel Drive', 'X-Mode', 'EyeSight Safety', 'Roof Rails', 'Harman Kardon Audio']
  },
  {
    id: 'bmw-x5-2020',
    make: 'BMW',
    model: 'X5',
    year: 2020,
    pricePerDay: 22000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    location: 'Lavington, Nairobi',
    imageUrl: 'https://images.unsplash.com/photo-1580273917197-8fb7ff3d4ab5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dG95b3RhJTIwcHJhZG98ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=600&q=60',
    features: ['xDrive', 'Live Cockpit Pro', 'Panoramic Sunroof', 'Parking Assistant', 'Gesture Control']
  }
];
// Bottom of the file
export const TRANSMISSION_TYPES = ['Automatic', 'Manual'];
export const FUEL_TYPES = ['Petrol', 'Diesel', 'Hybrid', 'Electric'];
export const LOCATIONS = [
  'Westlands, Nairobi',
  'Kilimani, Nairobi',
  'Karen, Nairobi',
  'Mombasa',
  'Upper Hill, Nairobi',
  'Nakuru',
  'Thika',
  'Gigiri, Nairobi',
  'Kisumu',
  'Naivasha',
  'Eastleigh, Nairobi',
  'Embakasi, Nairobi',
  'Runda, Nairobi',
  'Lavington, Nairobi'
];